### ISSUE TITLE
Howto install cudnn

### ISSUE THREAD

**Issue by mpkuse** [jetsonhacks/installTensorFlowTX2#17]
I am trying to source build tensorflow. All until buildSource.

./buildTensorFlow.sh
Cuda Configuration Error: cuDNN version detected from /usr/lib/aarch64-linux-gnu/include/cudnn.h (5.1.10) does not match TF_CUDNN_VERSION (6.0.21)
.

Is there a way to upgrade CuDNN without flashing my device with jetpack?

**Comment by ahmed-shariff** [comment]
you can use the jetpack to install cudnn without flashing. My experience of trying to work around jetpack was not fun, so :D

**Comment by mpkuse** [comment]
I trying to follow: https://developer.nvidia.com/nvidia-tensorrt3rc-download

Do you think I am on the correct path?

**Comment by ahmed-shariff** [comment]
are you downloading tensoRT separately? If my memory serves me correct, jetpack has tensorRT in it, right?

**Comment by mpkuse** [comment]
I am trying to install tensorflow following current repo. ie. from source code
https://github.com/jetsonhacks/installTensorFlowTX2

For some reason, my tx2 has cudnn5.1.10. However, tensorflow1.3 needs atleast cudnn6.
Hence, I am trying to install just cudnn6 for tx2

**Comment by ahmed-shariff** [comment]
Which jetpack version did you use to flash and install cudnn on the jetson? The jetpack 3.1 has cudnn 6. I believe using the jetpack is much easier than having to install cudnn manually. As far as I know, there is no direct download link of cudnn for tegra, which means you have to extract the links to the deb packages from the jetpack and download them separately, which did not have a happy ending for me :D. If you are stuck because you use a non ubuntu distro (which was my case, and I am way too lazy to install ubuntu on my pc ^_^), I found it easier to install ubuntu on a VM and then use jetpack, than trying to install stuff directly from my OS without using jetpack.

**Comment by jetsonhacks** [comment]
If you have cuDNN 5.1, then most likely you used JetPack 3.0, or did not flash the Jetson after you received it. There are issues simply installing cuDNN 6.0 over that install. 
There are two paths you can go by here:

You can build TensorFlow from source. This requires a new flash of the Jetson using JetPack 3.1. Here's the article: http://www.jetsonhacks.com/2017/09/14/build-tensorflow-on-nvidia-jetson-tx2-development-kit/

You can install a pre-compiled version of TensorFlow for the TX2 (saves a lot of time and headache): https://github.com/peterlee0127/tensorflow-tx2

As you noted, you will need to install cuDNN 6.0. JetPack 3.0 is a developers preview, it is *not* production software. NVIDIA recommends that you upgrade to JetPack 3.1 and the associated packages.
